# Generated by Django 6.0.3 on 2026-04-01 14:17

import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('information_ru', models.TextField(null=True)),
                ('information_ky', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('image_admin', models.ImageField(upload_to='admin_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_name_ru', models.CharField(max_length=100, null=True)),
                ('category_name_ky', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('category_icon', models.ImageField(upload_to='category_icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsup', models.URLField(blank=True)),
                ('phone_cafe', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG')),
                ('admin_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG')),
                ('insta_urls', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', multiselectfield.db.fields.MultiSelectField(choices=[('ПН', 'ПН'), ('ВТ', 'ВТ'), ('СР', 'СР'), ('ЧТ', 'ЧТ'), ('ПТ', 'ПТ'), ('СБ', 'СБ'), ('ВС', 'ВС')], max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_name_ru', models.CharField(max_length=100, null=True)),
                ('product_name_ky', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('gram', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150)),
                ('names_ru', models.CharField(max_length=150, null=True)),
                ('names_ky', models.CharField(max_length=150, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('age_work', models.PositiveSmallIntegerField()),
                ('dishes', models.PositiveSmallIntegerField()),
                ('link', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'Ресторан',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=127, null=True)),
                ('last_name', models.CharField(blank=True, max_length=127, null=True)),
                ('first_name', models.CharField(blank=True, max_length=127, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('user_role', models.CharField(choices=[('admin', 'admin'), ('client', 'client')], default='client', max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
            ],
        ),
        migrations.CreateModel(
            name='CafeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_image', models.ImageField(upload_to='cafe_images/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_images', to='caffe_app.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='caffe_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_ky', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('subimage', models.ImageField(upload_to='sub_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='caffe_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='caffe_app.subcategory'),
        ),
    ]
